### ISSUE TITLE
new function: authoriseGitHub ?

### ISSUE THREAD

**Issue by pbiecek** [MarcinKosinski/archivist.github#10]
In many examples you have:
# ' myapp <- oauth_app("github",
# '                    key = app_key,
# '                    secret = app_secret)
# ' github_token <- oauth2.0_token(oauth_endpoints("github"),
# '                                 myapp,
# '                                 scope = "public_repo")
# ' aoptions("github_token", github_token)

Instead of this one could use

authoriseGitHub(app_key, app_secret)

**Comment by pbiecek** [comment]
See c5b6fc74867255c1c8f4bc0913d8cc7c2cec539a for candidate function

**Comment by MarcinKosinski** [comment]
Sory for delay. I haven't seen issues and didn't got mail information.
I think it's better to ensure and add `@MarcinKosinski` to the issue description.
I think I'll turn e-mail notification for every action on this repo.

Thanks for suggestion and commit. Good idea :)
