### ISSUE TITLE
More verbose createGitHubRepo()

### ISSUE THREAD

**Issue by pbiecek** [MarcinKosinski/archivist.github#11]
Right now there are no messages about progress of createGitHubRepo().
If something is going wrong (i.e. R is just waiting...) it is hard to find out what is going on.
Proposition: adding verbose messages about current state
- creating an empty GitHub Repository
- initialize local git repository
  so on

**Comment by pbiecek** [comment]
candidate in 9c8ae99e865dee9889ef120d8e0edaff878e9228

**Comment by MarcinKosinski** [comment]
Thanks!
