### ISSUE TITLE
createGitHubRepo git2r issue

### ISSUE THREAD

**Issue by gse-cc-git** [MarcinKosinski/archivist.github#33]
Hello,
Trying to make a first use of `archivist.github`, 
when I run:

`` 
createGitHubRepo(repo="my-repo-name"
                  ,user="myusername"
                  ,password = "psswd"
                  ,github_token = github_token
                  ,repoDescription = "a desc"
                  ,default = TRUE)
``

 I get the following error message:

``
Error in default_signature(repo) : 
  Error in 'git2r_signature_default': Config value 'user.name' was not found
``

Any insight ?
Thanks by advance, and thank you for your work.

Below my sessionInfo:

``
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] git2r_0.18.0           httr_1.2.1             archivist.github_0.2.2 archivist_2.1.2       

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9     lubridate_1.6.0 withr_1.0.2     digest_0.6.10   bitops_1.0-6    R6_2.2.0        jsonlite_1.2   
 [8] DBI_0.5-1       magrittr_1.5    RSQLite_1.1-2   stringi_1.1.2   curl_2.3        rstudioapi_0.6  devtools_1.12.0
[15] tools_3.3.2     stringr_1.1.0   RCurl_1.95-4.8  memoise_1.0.0   openssl_0.9.6  `
``

**Comment by MarcinKosinski** [comment]
I will work on that with @krzyslom  tomorrow.
I think this also might be due to the fact that github API has been updated and know requires only 1 hash, instead of 2 hashes.

**Comment by MarcinKosinski** [comment]
@gse-cc-git how did you create `github_token` ? Have you used

````{R}
authoriseGitHub(ClientID, ClientSecret) -> github_token
````

Is your fixed when you also specify some additional default options for `archivist`/`archivist.github`  with

````{R}
aoptions("user", user.name)
aoptions("password", user.password)
````

**Comment by gse-cc-git** [comment]
Hi Marcin,

I'm sorry my testings where a bit messy, but what I found is that:
- I had to set the proxy parameters using `httr::set_config` and `httr::use_prox`
- I have to specify user, password and even repo and repoDir using `aoptions` because I did not seem to
work 

I used the following:

```
myapp <- oauth_app("github",
                   key = app_key,
                   secret = app_secret)

github_token <- oauth2.0_token(oauth_endpoints("github")
                               ,myapp
                               ,scope = c("public_repo"
                                          ,"delete_repo"))

aoptions("github_token",github_token)
```

I cannot figure out if the connexion to github is hardcoded in `archivist`
because the getRemoteHook function builds the url using `https://raw.githubusercontent.com`

Now, using `aoptions` for user,password,repo & repoDir I manage to have the `createGitHubRepo` work.
When I try to archive an artifact using `archive` I get the following steps completed:
- archive locally
- and new files for artifact
- commit
but
- push to github gives:


``
Error in .local(object, ...) : 
  Error in 'git2r_push': failed to send request: timeout
``

I cannot figure out if it has to do with being behind a proxy...

Thanks for your answer and your time.

cheers
C

**Comment by gse-cc-git** [comment]
Hello,
Any news ?
Thanks.

**Comment by MarcinKosinski** [comment]
I have tried the code locally on my machine and it creates and sends to the GitHub. I think this might be the issue with your firewall. Sorry for delay, I thought I have responded with such an answer.

By the way, do you normally can perform `git push` from bash or RStudio IDE?

**Comment by gse-cc-git** [comment]
Yes `git push` works from bash & RStudio.
Maybe it has to do with my SSHkey also. I have to recheck and let you know.
I'm learning those new things alltogether and get lost sometimes.. sorry
Thanks for your response anyway

**Comment by gse-cc-git** [comment]
Still the 'git2r_push' error.
Artifacts are correctly stored in the local repository but the pushing to my github remote repo fails.

I must get something wrong with the whole logic...

**Comment by gse-cc-git** [comment]
I was successful with the procedure from home. The environment is not exactly the same (os: linux) but there is no proxy.
Nevetheless I had to type
`git2r::config(repo="myreponame",user.name="myusername",user.email="myuseremail",global=TRUE)`

because I got a first `git2r` error complaining about missing user.name.

Were you successful from behind a proxy ?

**Comment by gse-cc-git** [comment]
I finally managed to test the process with the same environment (windows etc...) but using a direct connection (ie without using a proxy). It was successful.
My guess is that `git2r` or the `libgit2` it relies on cannot use the proxy settings... Far too complicates for me if it's true...

**Comment by MarcinKosinski** [comment]
@gse-cc-git for me too :) Thanks for the report. Maybe this is an issue for `git2r` package ?

**Comment by gse-cc-git** [comment]
@MarcinKosinski 
Issued there [#278](https://github.com/ropensci/git2r/issues/278)
^^

**Comment by MarcinKosinski** [comment]
Great, then let's close this issue then.
