### ISSUE TITLE
Professional  R Code Review

### ISSUE THREAD

**Issue by MarcinKosinski** [MarcinKosinski/archivist.github#7]
# About

`archivist.github` is a package that allows to archive R objects automatically on `GitHub` via `GitHub API` and `git2r` package. More or less one uses such code to archive his R object on `GitHub` from `R`:

``` R
createGitHubRepo(repo = "Gallery", default = TRUE) 
iris.lm.model <- lm(Sepal.Length ~ Sepal.Width + Petal.Length + Petal.Width,
                                        data= iris)
archive(iris.lm.model, alink = TRUE)
```

[archivist::aread('MarcinKosinski/Gallery/caab8f8e72045c93f92091aebcb74f2d')](https://raw.githubusercontent.com/MarcinKosinski/Gallery/master/gallery/caab8f8e72045c93f92091aebcb74f2d.rda)

``` R
showRemoteRepo(repo = 'Gallery', user = 'MarcinKosinski')[1:3, ]
                           md5hash                             name         createdDate
1 caab8f8e72045c93f92091aebcb74f2d                    iris.lm.model 2016-02-24 19:12:15
2 b0f870835c546853b70f921f57e100b4 b0f870835c546853b70f921f57e100b4 2016-02-24 19:12:15
3 7a761a2ae54f3d90060a9f6ca04b3506 7a761a2ae54f3d90060a9f6ca04b3506 2016-02-24 19:12:15
```
# Professional R Code Review

I am planning to upload ver `0.2` on CRAN so one better download this package from `GitHub`, so far:

``` R
devtools::install_github('MarcinKosinski/archivist.github')
```
## Review

I am developing so many packages that I run out of human resouces, concentration and perspective.
I would appreciate a feedback with user experience feelings. I am wondering whether documentation is complete, examples are well suited, web-site of the package is clear, or are there any functionalities that are missing, and whether the code is easy to proceed with updates for someone not working on this project normally. + Is the OAuth-token-creation well described in `man` and website?

I would appreciate pull-request with improvements and  new issues with user request or bugs detections. For those who will contribute in appropriately enough dedication I'll can guarantee mentioning that person in `NEWS.md` and, if deserved, in `DESCRIPTION` 

I can repay in writing a linkedin opinion, dinner invitation, proceeding with training with R or handing a bottle of rum (Havana, 3 years old).

**Comment by pbiecek** [comment]
Will work on this tomorrow

**Comment by MarcinKosinski** [comment]
Thank You very much. I'd really appreciate this effort (which isn't easy) :).

Marcin Kosinski

Dnia 23.03.2016 o godz. 19:47 Przemysław Biecek notifications@github.com napisał(a):

**Comment by MarcinKosinski** [comment]
Thanks for final checking. The next time, I'mt the one who invites for a dinner :)
